### ISSUE TITLE
Issue with downloading the song

### ISSUE THREAD

**Issue by raul1991** [tusharbabbar/gaana-dl#4]
The response in the get_song_url method is throwing the error while decoding the json which it isnt anymore. Check by printing the type(response). Plus i tried using the url that is being used in this method , seems like the api for gaana.com has changed.

Url
[Click here](http://api.gaana.com/getURLV1.php?quality=medium&album_id=1594081&delivery_type=stream&hashcode=5159b4212242279416844355d15284d4&isrc=0&type=rtmp&track_id=16663500)

Response
`{"status":0,"data":"Invalid Request.","quality":"na","error_code":"4003","error_msg":"HASH Code does not match","content_source":0}`

**Comment by sharmakhimlal** [comment]
Not able to download a single song from gaana.com

Traceback (most recent call last):
  File "gaana-dl.py", line 166, in <module>
    d.search_songs(args.song, args.dir)
  File "gaana-dl.py", line 98, in search_songs
    song_url = self._get_song_url(tracks_list[idx][1], tracks_list[idx][2])
  File "gaana-dl.py", line 50, in _get_song_url
    song_url_b64 = response.json()['data']
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 799, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ravibhoraniya** [comment]
how to find HASH Code only because i try it in php so plz help me.
